### PR TITLE
Fix memleaks

### PR DESCRIPTION
**Pull request by herr-biber**
Fix memory leaks.

`xdotool search --sync --name foo`

used to consume 15G of my memory after some hours of operation.

### CODE REVIEW

**Comment by h3xx** [comment]
Psst. Squash your commits.

**Comment by EvansMike** [comment]
Surely a better comment would be about the code and if this actually fixes the memory leaks?

**Comment by jordansissel** [comment]
I do not care about squashed commits. So don't worry :)

**Comment by herr-biber** [comment]
Hi Jordan,
is there anything I can do for this pull request to be ready to pull?

**Comment by jordansissel** [comment]
Code changes look OK. I haven't tested it (I'm not able to test right now), but based on the code looking ok I think this is good to merge :)

**Comment by herr-biber** [comment]
Thanks. I've tested the code over multiple days (while true; find window blocking, close window; done).

**Comment by jordansissel** [comment]
Awesome :)

Thank you for testing and helping make xdotool better!

**Pull request merged**
