### PR TITLE
Add Travis CI checks on compiling, installing and uninstalling

### PR DESCRIPTION
**Pull request by richelbilderbeek**
I always enjoy to be sure that my code is checked to compile upon a `git push`. And it demonstrates, in the `.travis.yml`, how to install and build the code. Even cooler: when others submit a Pull Request, it will be shown in GitHub if this breaks the build.

One drawback: you will need to activate Travis CI (go to www.travis-ci.org, sign in with you GitHub account and activate the `xdotool` repository). I am willing to maintain the `.travis.yml` script, as I have [plenty of experience with it](https://github.com/richelbilderbeek/travis_cpp_tutorial).

### CODE REVIEW

**Comment by jordansissel** [comment]
Travis is a great product. However, it is often too hard to reproduce
failures that occur on Travis, so I don't use it for some of my projects.

**Comment by richelbilderbeek** [comment]
Then do you recommend another CI service?

If not, to me it feels you may be throwing the child away with the bath water. But well, you're the boss :-)

**Comment by jordansissel** [comment]
I am ok with running tests locally, for me. For this project, I am OK
merging your change but I am likely to only use the Travis result as
informative, not blocking or required.

If it helps others test, I am happy to merge.

**Comment by richelbilderbeek** [comment]
Great! I'd love that! You'll see I'll add some more tests to help -at least- me.

**Pull request merged**
