### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by robkam**
To save people from wasting their time trying to use this with Wayland.

### CODE REVIEW

**Comment by jordansissel** [comment]
I agree with the idea of this change but not the content of the change itself. The wording (my words copied from a comment in 2020?) may not be accurate with respect to Wayland's capabilities. A simpler "This tool does not work under Wayland" could be better.

A separate change that might help is having xdotool detect if it is being run under Wayland, and if so, reporting directly to the user that it doesn't work.

**Comment by jordansissel** [comment]
#343 updates the readme with a warning about wayland.

Thanks for helping make xdotool better :)

**Comment by jordansissel** [comment]
> having xdotool detect if it is being run under Wayland

fwiw this is now detected with #342 merged.

**Comment by robkam** [comment]
Thanks :-)

**Pull request closed without merging**
