### PR TITLE
Use `grep -E` instead of `egrep`

### PR DESCRIPTION
**Pull request by a1346054**
And remove `egrep` where regular `grep` is enough.

### CODE REVIEW

**Comment by sskras** [comment]
Not to oppose this, but not all ***nices** support the `-E` switch. Eg. older Solaris does not:
https://docs.oracle.com/cd/E23823_01/html/816-5165/grep-1.html

**Comment by a1346054** [comment]
Older solaris should use older xdotool, or users of older solaris should make sure to have /usr/xpg4/bin/grep which does support `-E`.

Current GNU grep reports a deprecation message on invocation.

https://lists.gnu.org/archive/html/info-gnu/2022-09/msg00001.html

> The egrep and fgrep commands, which have been deprecated since
  release 2.5.3 (2007), now warn that they are obsolescent and should
  be replaced by grep -E and grep -F.

The message is sent to stderr and looks like this:

> egrep: warning: egrep is obsolescent; using grep -E

**Comment by sskras** [comment]
> Older solaris should use older xdotool, or users of older solaris should make sure to have /usr/xpg4/bin/grep which does support `-E`.

Maybe it should be mentioned in the README or so? :)

> Current GNU grep reports a deprecation message on invocation.

With all due respect, GNU is only a flavor or *nix userland, one among several rivals.

**Comment by a1346054** [comment]
I can prepare something for the README, but currently there's no mention of solaris, HP-UX, AIX, Xenix, ... anywhere in the current codebase of xdotool.

**Comment by jordansissel** [comment]
+1 on this change to reduce that deprecation warning.

**Pull request merged**
