### PR TITLE
fix memory leak

### PR DESCRIPTION
**Pull request by luxe**
XkbFreeClientMap -> XkbFreeKeyboard

### CODE REVIEW

**Comment by FascinatedBox** [comment]
@jordansissel Tested this patch. It still applies, and it fixes a memory leak.

**Comment by jordansissel** [comment]
Odd. Maybe this is a documentation (or implementation) bug in X11? The documentation for XkbGetMap shows:

> To free the returned data, use XkbFreeClientMap.

So it should be "correct" to do what xdo is already doing, and yet, it leaks, as y'all have shown. Weird!

I thought about filing something upstream on X11, but it feels like that project is trying to self-terminate so I don't know if it'd be anything they would bother addresseing.

**Comment by jordansissel** [comment]
Thanks for this fix, btw! Also thanks to @FascinatedBox for testing <3

**Comment by jordansissel** [comment]
I made some sample code to reproduce this leak using only X11 libraries -- should someone wish to pursue this leak upstream with Xorg.

https://github.com/jordansissel/xdotool/issues/385#issuecomment-1220163564

**Pull request merged**
